/**
 * The `--manual` checklist (`00 §7` cut line 2: static per-criterion
 * checklist, no page-context derivation - `types.ts`'s `PageFeatures`/
 * `ManualCheck.appliesWhen` stay unevaluated, "roadmap-gated, unused in
 * v1"). One data source (`wcag/coverage.ts`'s `manualChecks`) drives the
 * README table, the coverage matrix and this checklist (`03 §1.8`).
 *
 * Three layers, in order: the static criterion-keyed checklist (every
 * `WCAG_COVERAGE` entry's real prompts, unfiltered by page); then, when a
 * `Report` is supplied, that run's own needs-review findings and
 * probe-blind regions, routed in per page - the things THIS run actually
 * needs a human to look at, not just the general checklist every run
 * would print identically.
 */

import { TOOL_NAME, TOOL_VERSION } from '../meta.js';
import { criterionById } from '../wcag/criteria.js';
import { WCAG_COVERAGE } from '../wcag/coverage.js';
import type { ManualOptions, Report } from '../types.js';

interface ChecklistCriterion {
  id: string;
  title: string;
  level: string;
  status: string;
  note: string;
  checks: Array<{ id: string; prompt: string; method: string }>;
}

interface ChecklistPageFindings {
  url: string;
  needsReview: Array<{ ruleId: string; selector: string; remediation: string; criteria: string[] }>;
  blindRegions: Array<{ selector: string; reason: string; unevaluatedCriteria: string[] }>;
}

interface ChecklistData {
  criteria: ChecklistCriterion[];
  /** Present only when a `Report` was supplied. */
  pages?: ChecklistPageFindings[];
}

function buildChecklistData(options: ManualOptions, report?: Report): ChecklistData {
  const idFilter = options.criteria ? new Set(options.criteria) : undefined;

  const criteria = WCAG_COVERAGE.filter((entry) => !idFilter || idFilter.has(entry.criterion)).map((entry) => {
    const criterion = criterionById(entry.criterion);
    return {
      id: entry.criterion,
      title: criterion?.title ?? entry.criterion,
      level: criterion?.level ?? '?',
      status: entry.status,
      note: entry.note,
      checks: entry.manualChecks.map((check) => ({ id: check.id, prompt: check.prompt, method: check.method })),
    };
  });

  if (!report) {
    return { criteria };
  }

  const pages = report.pages
    .map((page): ChecklistPageFindings => {
      const needsReview = report.findings
        .filter(
          (finding) =>
            finding.url === page.url &&
            finding.bucket === 'needs-review' &&
            !finding.suppressed &&
            (!idFilter || finding.criteria.some((c) => idFilter.has(c.id))),
        )
        .map((finding) => ({
          ruleId: finding.ruleId,
          selector: finding.selector,
          remediation: finding.remediation,
          criteria: finding.criteria.map((c) => c.id),
        }));

      const blindRegions = page.probeBlindRegions
        .filter((region) => !idFilter || region.unevaluatedCriteria.some((id) => idFilter.has(id)))
        .map((region) => ({
          selector: region.selector,
          reason: region.reason,
          unevaluatedCriteria: region.unevaluatedCriteria,
        }));

      return { url: page.url, needsReview, blindRegions };
    })
    .filter((page) => page.needsReview.length > 0 || page.blindRegions.length > 0);

  return { criteria, pages };
}

function renderMarkdown(data: ChecklistData): string {
  const lines: string[] = [
    '# Manual accessibility checklist',
    '',
    `Generated by ${TOOL_NAME} ${TOOL_VERSION}. These are the criteria this tool does not claim ` +
      'to test automatically. Working through this checklist is not a conformance evaluation ' +
      'either - it is a structured pass by a person, which is the only thing that reaches most ' +
      'of WCAG.',
    '',
    '## Criteria requiring manual verification',
  ];

  for (const criterion of data.criteria) {
    lines.push('', `### ${criterion.id} ${criterion.title} [${criterion.level}]`, '', `_${criterion.status}_ — ${criterion.note}`, '');
    for (const check of criterion.checks) {
      lines.push(`- [ ] (${check.method}) ${check.prompt}`);
    }
  }

  if (data.pages) {
    lines.push('', '## Findings and blind regions, by page');
    if (data.pages.length === 0) {
      lines.push('', 'No needs-review findings or probe-blind regions in this report.');
    }
    for (const page of data.pages) {
      lines.push('', `### ${page.url}`);
      if (page.needsReview.length > 0) {
        lines.push('', '**Needs-review — verify these:**', '');
        for (const finding of page.needsReview) {
          const criteriaLabel = finding.criteria.length > 0 ? finding.criteria.join(', ') : 'no SC mapped';
          lines.push(`- [ ] [${finding.ruleId}] \`${finding.selector}\` (${criteriaLabel}) — ${finding.remediation}`);
        }
      }
      if (page.blindRegions.length > 0) {
        lines.push('', '**Could not evaluate — check by hand:**', '');
        for (const region of page.blindRegions) {
          lines.push(`- [ ] \`${region.selector}\` — ${region.reason} (unevaluated: ${region.unevaluatedCriteria.join(', ')})`);
        }
      }
    }
  }

  return lines.join('\n');
}

/** Renders the manual checklist, filtered to `options.criteria` when given, with per-page routing when `report` is given. */
export function renderManualChecklist(options: ManualOptions, report?: Report): string {
  const data = buildChecklistData(options, report);
  return options.format === 'json' ? JSON.stringify(data, null, 2) : renderMarkdown(data);
}
